const path = require('path')
const a = path.basename('C:\\temp\\index.js')
const a1 = path.dirname('C:\\temp\\index.js')
const a2 = path.extname('__filename')
console.log(a)
console.log(a1)
console.log(__filename,a2)